[connections.snowflake]
account = "TKGLEDD-JVB73331"
user = "shirisham"
password = "Snowflake_sc1!123"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
CLIENT_SESSION_KEEP_ALIVE= TRUE
